/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:35918435-7f6c-4ba3-ad6c-59bc7d79d235",
    "aws_cognito_region": "us-east-1",
    "oauth": {},
    "aws_mobile_analytics_app_id": "966de74975fb48dbaf809a347664e636",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
